export const rooms = {
    "en": [
        {value: 'Family Room', label: 'Family Room'},
        {value: 'Den', label: 'Den'},
        {value: 'Living Room', label: 'Living Room'},
        {value: 'Dining Room', label: 'Dining Room'},
        {value: 'Kitchen', label: 'Kitchen'},
        {value: 'Pantry', label: 'Pantry'},
        {value: 'Breakfast Nook', label: 'Breakfast Nook'},
        {value: 'Main Bedroom', label: 'Main Bedroom'},
        {value: 'Bedroom1', label: 'Bedroom1'},
        {value: 'Bedroom2', label: 'Bedroom2'},
        {value: 'Bedroom3', label: 'Bedroom3'},
        {value: 'Bedroom4', label: 'Bedroom4'},
        {value: 'Bedroom5', label: 'Bedroom5'},
        {value: 'Closet', label: 'Closet'},
        {value: 'Main Bathroom', label: 'Main Bathroom'},
        {value: 'Bathroom1', label: 'Bathroom1'},
        {value: 'Bathroom2', label: 'Bathroom2'},
        {value: 'Bathroom3', label: 'Bathroom3'},
        {value: 'Bathroom4', label: 'Bathroom4'},
        {value: 'Bathroom5', label: 'Bathroom5'},
        {value: 'Office', label: 'Office'},
        {value: 'Basement', label: 'Basement'},
        {value: 'Entry', label: 'Entry'},
        {value: 'Mud Room', label: 'Mud Room'},
        {value: 'Hall', label: 'Hall'},
        {value: 'Media', label: 'Media'},
        {value: 'Laundry', label: 'Laundry'},
        {value: 'Nursery', label: 'Nursery'},
        {value: 'Study', label: 'Study'},
        {value: 'Waiting Room', label: 'Waiting Room'},
        {value: 'Garage', label: 'Garage'},
        {value: 'Storage Room', label: 'Storage Room'},
        {value: 'Attic', label: 'Attic'},
        {value: 'Powder Room', label: 'Powder Room'},
        {value: 'Guest Bedroom', label: 'Guest Bedroom'},
        {value: 'Guest room', label: 'Guest room'},
        {value: 'Sunroom', label: 'Sunroom'},
        {value: 'Playroom', label: 'Playroom'},
        {value: 'Kidroom1', label: 'Kidroom1'},
        {value: 'Kidroom2', label: 'Kidroom2'},
        {value: 'Kidroom3', label: 'Kidroom3'},
        {value: 'Kidroom4', label: 'Kidroom4'},
        {value: 'Kidroom5', label: 'Kidroom5'},
        {value: 'Gym', label: 'Gym'},
        {value: 'Pool House', label: 'Pool House'},
        {value: 'ADU', label: 'ADU'},
        {value: 'Stairway', label: 'Stairway'},
        {value: 'Other', label: 'Other'}
    ],
    "fa": [
        {value: 'Family Room', label: 'اتاق خانواده'},
        {value: 'Den', label: 'خلوتگاه'},
        {value: 'Living Room', label: 'اتاق نشیمن'},
        {value: 'Dining Room', label: 'غذاخوری'},
        {value: 'Kitchen', label: 'آشپزخانه'},
        {value: 'Pantry', label: 'آبدارخانه'},
        {value: 'Breakfast Nook', label: 'گوشه صبحانه'},
        {value: 'Main Bedroom', label: 'اتاق خواب اصلی'},
        {value: 'Bedroom1', label: 'اتاق خواب ۱'},
        {value: 'Bedroom2', label: 'اتاق خواب ۲'},
        {value: 'Bedroom3', label: 'اتاق خواب ۳'},
        {value: 'Bedroom4', label: 'اتاق خواب ۴'},
        {value: 'Bedroom5', label: 'اتاق خواب ۵'},
        {value: 'Closet', label: 'کمد لباس'},
        {value: 'Main Bathroom', label: 'سرویس بهداشتی اصلی'},
        {value: 'Bathroom1', label: 'سرویس بهداشتی ۱'},
        {value: 'Bathroom2', label: 'سرویس بهداشتی ۲'},
        {value: 'Bathroom3', label: 'سرویس بهداشتی ۳'},
        {value: 'Bathroom4', label: 'سرویس بهداشتی ۴'},
        {value: 'Bathroom5', label: 'سرویس بهداشتی ۵'},
        {value: 'Office', label: 'دفتر'},
        {value: 'Basement', label: 'زیر زمین'},
        {value: 'Entry', label: 'ورودی'},
        {value: 'Mud Room', label: 'اتاق گلی'},
        {value: 'Hall', label: 'هال'},
        {value: 'Media', label: 'رسانه'},
        {value: 'Laundry', label: 'خشکشویی'},
        {value: 'Nursery', label: 'مهد کودک'},
        {value: 'Study', label: 'کتابخانه'},
        {value: 'Waiting Room', label: 'اتاق انتظار'},
        {value: 'Garage', label: 'کاراژ'},
        {value: 'Storage Room', label: 'انبار'},
        {value: 'Attic', label: 'اتاق زیر شیروانی'},
        {value: 'Powder Room', label: 'توالت زنانه'},
        {value: 'Guest Bedroom', label: 'اتاق خواب مهمان'},
        {value: 'Guest room', label: 'اتاق مهمان'},
        {value: 'Sunroom', label: 'اتاق افتاب رو'},
        {value: 'Playroom', label: 'اتاق بازی'},
        {value: 'Kidroom1', label: 'اتاق کودک ۱'},
        {value: 'Kidroom2', label: 'اتاق کودک ۲'},
        {value: 'Kidroom3', label: 'اتاق کودک ۳'},
        {value: 'Kidroom4', label: 'اتاق کودک ۴'},
        {value: 'Kidroom5', label: 'اتاق کودک ۵'},
        {value: 'Gym', label: 'باشگاه'},
        {value: 'Pool House', label: 'استخر خانه'},
        {value: 'ADU', label: 'واحد مسکونی لوازم جانبی'},
        {value: 'Stairway', label: 'راه پله'},
        {value: 'Other', label: 'دیگر'}
    ]
};

